/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsSvg {
        /**
          * svg size in px, em, rem, %,...
         */
        "size": string;
        /**
          * asset as string
         */
        "svg": string;
        /**
          * asset url,can be relative or absolute
         */
        "url": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDsSvgElement extends Components.DsSvg, HTMLStencilElement {
    }
    var HTMLDsSvgElement: {
        prototype: HTMLDsSvgElement;
        new (): HTMLDsSvgElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ds-svg": HTMLDsSvgElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DsSvg {
        /**
          * svg size in px, em, rem, %,...
         */
        "size"?: string;
        /**
          * asset as string
         */
        "svg"?: string;
        /**
          * asset url,can be relative or absolute
         */
        "url"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ds-svg": DsSvg;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-svg": LocalJSX.DsSvg & JSXBase.HTMLAttributes<HTMLDsSvgElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
